2025-04-09 04:14:27,860 - ERROR - Request error: HTTPSConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /register (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x704f1b37c8f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-09 04:14:27,860 - ERROR - Registration error: HTTPSConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /register (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x704f1b37c8f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-09 04:18:09,934 - ERROR - Request error: HTTPSConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /register (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7dcf7495e5a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-09 04:18:09,934 - ERROR - Registration error: HTTPSConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /register (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7dcf7495e5a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-09 04:18:50,353 - ERROR - Request error: HTTPSConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /register (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1000)')))
2025-04-09 04:18:50,353 - ERROR - Registration error: HTTPSConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /register (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1000)')))
2025-04-09 12:28:54,844 - ERROR - Request error: HTTPSConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /register (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:992)')))
2025-04-09 12:28:54,844 - ERROR - Registration error: HTTPSConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /register (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:992)')))
2025-04-09 12:33:23,259 - ERROR - Request error: HTTPSConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /register (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:992)')))
2025-04-09 12:33:23,259 - ERROR - Registration error: HTTPSConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /register (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:992)')))
2025-04-09 12:34:09,310 - ERROR - Request error: HTTPSConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /register (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000228A51B73D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-09 12:34:09,310 - ERROR - Registration error: HTTPSConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /register (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000228A51B73D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-09 12:34:23,825 - ERROR - Request error: HTTPSConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /register (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:992)')))
2025-04-09 12:34:23,825 - ERROR - Registration error: HTTPSConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /register (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:992)')))
2025-04-09 12:35:16,936 - ERROR - Request error: HTTPSConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /login (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:992)')))
2025-04-09 12:35:16,936 - ERROR - Login error: HTTPSConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /login (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:992)')))
2025-04-09 12:37:29,071 - ERROR - Request error: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2025-04-09 12:37:29,071 - ERROR - Registration error: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2025-04-09 12:37:56,183 - ERROR - Request error: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2025-04-09 12:37:56,184 - ERROR - Registration error: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2025-04-09 12:38:06,249 - ERROR - Request error: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2025-04-09 12:38:06,249 - ERROR - Registration error: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2025-04-09 12:39:27,761 - ERROR - Request error: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2025-04-09 12:39:27,761 - ERROR - Registration error: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2025-04-09 12:44:12,863 - ERROR - Request error: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2025-04-09 12:44:12,863 - ERROR - Registration error: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2025-04-09 12:44:29,049 - ERROR - Request error: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2025-04-09 12:44:29,049 - ERROR - Registration error: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2025-04-09 12:46:36,643 - ERROR - Request error: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /register (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001925AFE7450>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-09 12:46:36,643 - ERROR - Registration error: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /register (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001925AFE7450>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
