2025-04-09 04:14:27,860 - ERROR - Request error: HTTPSConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /register (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x704f1b37c8f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-09 04:14:27,860 - ERROR - Registration error: HTTPSConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /register (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x704f1b37c8f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-09 04:18:09,934 - ERROR - Request error: HTTPSConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /register (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7dcf7495e5a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-09 04:18:09,934 - ERROR - Registration error: HTTPSConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /register (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7dcf7495e5a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-09 04:18:50,353 - ERROR - Request error: HTTPSConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /register (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1000)')))
2025-04-09 04:18:50,353 - ERROR - Registration error: HTTPSConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /register (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1000)')))
